'use strict';
// Regression tests for background.js's pure/testable logic. background.js is a service
// worker (not a CommonJS module), so it's loaded via node:vm into a minimal stub context,
// matching the pattern already used for scraper.js/viewer.js.
//
// Run with:  node --test background.test.js

const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');

const EXTENSION_ID = 'abcdefghijklmnopqrstuvwxyzabcdef';

function loadBackgroundContext({ namespace = 'chrome', environment = 'service-worker' } = {}) {
  const bgSrc = fs.readFileSync(path.join(__dirname, 'background.js'), 'utf8');
  const utilsSrc = fs.readFileSync(path.join(__dirname, 'utils.js'), 'utf8');
  const scheme = namespace === 'browser' ? 'moz-extension' : 'chrome-extension';
  const urlHost = namespace === 'browser' ? '01234567-89ab-cdef-0123-456789abcdef' : EXTENSION_ID;
  const api = {
    runtime: {
      id: EXTENSION_ID,
      getURL(p) { return `${scheme}://${urlHost}/${p}`; },
      onMessage: { addListener(fn) { sandbox._messageListener = fn; } },
    },
    action: { onClicked: { addListener(fn) { sandbox._actionListener = fn; } } },
    tabs: { query: async () => [], update: async () => {}, create: async () => {} },
    windows: { update: async () => {} },
    scripting: { executeScript: async () => [{ result: null }] },
    storage: { local: { get: async () => ({}), set: async () => {}, remove: async () => {} } },
  };
  const sandbox = {
    console,
    URL,
    _api: api,
    _utilsLoadCount: 0,
  };
  sandbox[namespace] = api;
  const context = vm.createContext(sandbox);
  if (environment === 'service-worker') {
    sandbox.importScripts = (file) => {
      assert.equal(file, 'utils.js');
      sandbox._utilsLoadCount += 1;
      vm.runInContext(utilsSrc, context, { filename: file });
    };
  } else {
    sandbox._utilsLoadCount += 1;
    vm.runInContext(utilsSrc, context, { filename: 'utils.js' });
  }
  vm.runInContext(bgSrc, context, { filename: 'background.js' });
  return context;
}

function trustedSender(overrides = {}, { scheme = 'chrome-extension', host = EXTENSION_ID } = {}) {
  return {
    id: EXTENSION_ID,
    tab: { id: 7 },
    url: `${scheme}://${host}/viewer.html`,
    ...overrides,
  };
}

test('background initializes through chrome in a service-worker environment and imports utils once', () => {
  const ctx = loadBackgroundContext({ namespace: 'chrome', environment: 'service-worker' });
  assert.equal(ctx.ext, ctx.chrome);
  assert.equal(ctx._utilsLoadCount, 1);
  assert.equal(typeof ctx._actionListener, 'function');
});

test('background initializes through browser in a Firefox background-script environment without reloading utils', () => {
  const ctx = loadBackgroundContext({ namespace: 'browser', environment: 'background-script' });
  assert.equal(ctx.ext, ctx.browser);
  assert.equal(ctx._utilsLoadCount, 1);
  assert.equal(typeof ctx._messageListener, 'function');
});

test('isTrustedViewerSender accepts a message from the packaged viewer page', () => {
  const ctx = loadBackgroundContext();
  assert.equal(ctx.isTrustedViewerSender(trustedSender()), true);
});

test('isTrustedViewerSender accepts Firefox packaged viewer URL generated by runtime.getURL', () => {
  const ctx = loadBackgroundContext({ namespace: 'browser', environment: 'background-script' });
  const host = '01234567-89ab-cdef-0123-456789abcdef';
  assert.equal(ctx.isTrustedViewerSender(trustedSender({}, { scheme: 'moz-extension', host })), true);
});

test('isTrustedViewerSender rejects a different extension id, a non-tab sender, and a non-viewer path', () => {
  const ctx = loadBackgroundContext();
  assert.equal(ctx.isTrustedViewerSender(trustedSender({ id: 'someOtherExtensionId12345678901' })), false);
  assert.equal(ctx.isTrustedViewerSender(trustedSender({ tab: undefined })), false, 'no tab.id (e.g. a devtools panel) must not pass');
  assert.equal(ctx.isTrustedViewerSender(trustedSender({ url: `chrome-extension://${EXTENSION_ID}/background.js` })), false, 'not the viewer page');
  assert.equal(ctx.isTrustedViewerSender(trustedSender({ url: 'https://evil.example.com/viewer.html' })), false, 'wrong protocol/origin entirely');
  assert.equal(ctx.isTrustedViewerSender(trustedSender({ url: 'not a valid URL' })), false, 'malformed URL');
  assert.equal(ctx.isTrustedViewerSender(null), false);
  assert.equal(ctx.isTrustedViewerSender(undefined), false);
});

test('the SCRAPE_PAGE message listener rejects an untrusted sender without ever calling scrapeActiveTab', () => {
  const ctx = loadBackgroundContext();
  let scrapeActiveTabCalled = false;
  ctx.scrapeActiveTab = async () => { scrapeActiveTabCalled = true; return { ok: true }; };

  let responded = null;
  const keepChannelOpen = ctx._messageListener(
    { type: 'SCRAPE_PAGE' },
    trustedSender({ id: 'wrongExtensionId1234567890123456' }),
    (response) => { responded = response; },
  );

  assert.equal(scrapeActiveTabCalled, false, 'an untrusted sender must never trigger a scrape');
  assert.equal(responded.ok, false);
  assert.ok(responded.errors[0].includes('unexpected sender'));
  // No async work was started for a rejected sender, so the listener should not keep the
  // message channel open waiting for a later sendResponse call.
  assert.notEqual(keepChannelOpen, true);
});

test('the SCRAPE_PAGE message listener proceeds normally for a trusted sender', async () => {
  const ctx = loadBackgroundContext();
  let scrapeActiveTabCalled = false;
  ctx.scrapeActiveTab = async () => { scrapeActiveTabCalled = true; return { ok: true, narrative: 'x' }; };

  let responded = null;
  const keepChannelOpen = ctx._messageListener(
    { type: 'SCRAPE_PAGE' },
    trustedSender(),
    (response) => { responded = response; },
  );
  assert.equal(keepChannelOpen, true, 'the real async path keeps the channel open for the later sendResponse');
  await new Promise(r => setTimeout(r, 0)); // let the scrapeActiveTab().then(sendResponse) microtask settle
  assert.equal(scrapeActiveTabCalled, true);
  assert.equal(responded.ok, true);
});

// sanitizeScrapeResult guards against scraper.js's result: scraper.js runs injected into
// FinalWhistle's own page, sharing that page's JS realm, so a compromised or just buggy
// page could tamper with what comes back (including prototype pollution) before it's
// trusted and stored. Per this project's graceful-degradation philosophy, only a
// fundamentally hostile top-level shape is rejected outright (returns null) — anything
// merely oversized-but-plausible is truncated with a warning instead of thrown away.

function basicScrape(overrides = {}) {
  return {
    ok: true,
    errors: [],
    warnings: [],
    narrative: 'Some narrative text.',
    telemetry: 'Some telemetry text.',
    statistics: { Possession: { home: '54%', away: '46%' } },
    initialTactics: { home: { mentality: 'NORMAL', style: 'SHORT_PASSES', marking: 'ZONE', defenceFocus: 'NORMAL', preferredSide: 'NORMAL' },
                       away: { mentality: 'NORMAL', style: 'THROUGH_BALLS', marking: 'ZONE', defenceFocus: 'NORMAL', preferredSide: 'NORMAL' } },
    homeTeam: 'Home FC',
    awayTeam: 'Away FC',
    url: 'https://www.finalwhistle.org/en/match/abc',
    scrapedAt: 1700000000000,
    ...overrides,
  };
}

// sanitizeScrapeResult's isPlainRecord check compares Object.getPrototypeOf(value)
// against THIS vm context's own Object.prototype — a plain object literal built in the
// outer Node realm (like basicScrape()'s return value) carries a DIFFERENT realm's
// Object.prototype and would be (mis)treated as hostile. Round-tripping through the
// context's own JSON reconstructs the object inside the right realm, matching what
// actually happens in production (scripting.executeScript structured-clones its
// result into background.js's own realm).
//
// Note: JSON/Object/etc. are reachable by bare identifier from CODE running inside a vm
// context, but are not exposed as own properties of the sandbox object itself (so
// ctx.JSON is undefined from the host side) — hence running the parse via
// vm.runInContext rather than calling ctx.JSON.parse directly.
function inRealm(ctx, value) {
  const encoded = JSON.stringify(JSON.stringify(value));
  return vm.runInContext(`JSON.parse(${encoded})`, ctx);
}

test('sanitizeScrapeResult passes a well-formed scrape through unchanged', () => {
  const ctx = loadBackgroundContext();
  const input = basicScrape();
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, input));
  assert.equal(JSON.stringify(out), JSON.stringify(input));
});

test('sanitizeScrapeResult rejects a fundamentally hostile top-level shape', () => {
  const ctx = loadBackgroundContext();
  assert.equal(ctx.sanitizeScrapeResult(null), null);
  assert.equal(ctx.sanitizeScrapeResult(undefined), null);
  assert.equal(ctx.sanitizeScrapeResult('a string, not a record'), null);
  assert.equal(ctx.sanitizeScrapeResult([1, 2, 3]), null, 'an array must not be treated as a record');
  assert.equal(ctx.sanitizeScrapeResult(basicScrape({ narrative: 12345 })), null, 'narrative with the wrong type entirely is hostile, not just oversized');
  assert.equal(ctx.sanitizeScrapeResult(basicScrape({ telemetry: {} })), null);

  const polluted = Object.create({ evil: true });
  Object.assign(polluted, basicScrape());
  assert.equal(ctx.sanitizeScrapeResult(polluted), null, 'an object whose prototype was tampered with must be rejected');
});

test('sanitizeScrapeResult truncates oversized narrative/telemetry/team names and warns about it', () => {
  const ctx = loadBackgroundContext();
  // SCRAPE_LIMITS is a top-level `const` in background.js, so (unlike its function
  // declarations) it never attaches to the sandbox object — read it via runInContext.
  const limits = vm.runInContext('SCRAPE_LIMITS', ctx);
  const longNarrative = 'x'.repeat(limits.narrativeChars + 500);
  const longName = 'y'.repeat(limits.teamNameChars + 20);
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, basicScrape({ narrative: longNarrative, homeTeam: longName })));

  assert.equal(out.narrative.length, limits.narrativeChars);
  assert.equal(out.homeTeam.length, limits.teamNameChars);
  assert.ok(out.warnings.some(w => w.includes('narrative')), 'a truncation warning must be surfaced, not silently applied');
  assert.ok(out.warnings.some(w => w.includes('homeTeam')));
});

test('sanitizeScrapeResult drops a malformed statistics object to null instead of rejecting the whole scrape', () => {
  const ctx = loadBackgroundContext();
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, basicScrape({ statistics: { Possession: { home: '54%' } } }))); // missing "away"
  assert.equal(out.statistics, null);
  assert.equal(out.narrative, 'Some narrative text.', 'the rest of the scrape must still come through');
});

test('sanitizeScrapeResult drops an unknown field and non-string values out of initialTactics without rejecting the whole scrape', () => {
  const ctx = loadBackgroundContext();
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, basicScrape({
    initialTactics: {
      home: { mentality: 'ATTACKING', style: 42, offside: 'ZONAL' }, // offside isn't a known field; style isn't a string
      away: null,
    },
  })));
  assert.equal(JSON.stringify(out.initialTactics), JSON.stringify({ home: { mentality: 'ATTACKING' }, away: {} }));
});

test('sanitizeScrapeResult treats a hostile (non-record) initialTactics as absent, not fatal', () => {
  const ctx = loadBackgroundContext();
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, basicScrape({ initialTactics: 'not an object' })));
  assert.equal(out.initialTactics, null);
  assert.equal(out.ok, true, 'a malformed optional field must not sink an otherwise-usable scrape');
});

test('sanitizeScrapeResult filters non-string entries out of errors/warnings and recomputes ok from the cleaned errors', () => {
  const ctx = loadBackgroundContext();
  const out = ctx.sanitizeScrapeResult(inRealm(ctx, basicScrape({
    ok: true, // deliberately inconsistent with errors below, to prove ok is recomputed, not trusted
    errors: ['REAL_ERROR', { injected: 'object' }, 42],
  })));
  assert.equal(JSON.stringify(out.errors), JSON.stringify(['REAL_ERROR']));
  assert.equal(out.ok, false, 'ok must reflect the sanitized errors array, not the scraper-supplied flag');
});

test('runScraper() falls back to "No result from scraper" when the injected script returns a hostile shape', async () => {
  const ctx = loadBackgroundContext();
  ctx.chrome.scripting.executeScript = async () => [{ result: inRealm(ctx, ['not', 'a', 'record']) }];
  let stored = 'not called';
  ctx.chrome.storage.local.set = async (value) => { stored = value; };

  const data = await ctx.runScraper(7);
  assert.equal(data.ok, false);
  // data.errors was built inside the vm context, so compare by value (see the
  // cross-realm note on inRealm above) rather than assert.deepEqual.
  assert.equal(JSON.stringify(data.errors), JSON.stringify(['No result from scraper']));
  assert.equal(stored, 'not called', 'a rejected scrape must never be persisted');
});

test('runScraper() sanitizes and stores a well-formed scrape result', async () => {
  const ctx = loadBackgroundContext();
  ctx.chrome.scripting.executeScript = async () => [{ result: inRealm(ctx, basicScrape()) }];
  let stored = null;
  ctx.chrome.storage.local.set = async (value) => { stored = value; };

  const data = await ctx.runScraper(7);
  assert.equal(data.ok, true);
  assert.equal(stored.lastScrape.narrative, 'Some narrative text.');
  assert.equal(stored.lastScrape.schemaVersion, 1);
});

test('runScraper uses Promise-based scripting and storage through the Firefox browser namespace', async () => {
  const ctx = loadBackgroundContext({ namespace: 'browser', environment: 'background-script' });
  ctx.browser.scripting.executeScript = async () => [{ result: inRealm(ctx, basicScrape()) }];
  let stored = null;
  ctx.browser.storage.local.set = async value => { stored = value; };

  const data = await ctx.runScraper(7);
  assert.equal(data.ok, true);
  assert.equal(stored.lastScrape.schemaVersion, 1);
});

test('mostRecentlyAccessed falls back safely when lastAccessed is unavailable', () => {
  const ctx = loadBackgroundContext();
  assert.equal(ctx.mostRecentlyAccessed([{ id: 1 }, { id: 2 }]), null, 'unordered tabs must not be chosen arbitrarily');
  assert.equal(ctx.mostRecentlyAccessed([{ id: 1 }, { id: 2, active: true }]).id, 2);
  assert.equal(ctx.mostRecentlyAccessed([{ id: 1 }]).id, 1);
  assert.equal(ctx.mostRecentlyAccessed([{ id: 1, lastAccessed: 5 }, { id: 2, lastAccessed: 9 }]).id, 2);
});
